[package]
name = "kite-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
twilight-model = "0.11.0"
twilight-gateway = "0.11.0"
twilight-http = "0.11.0"
twilight-cache-inmemory = "0.11.0"
tokio = "1.19.2"
