[package]
name = "kite-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
kite-engine = { path = "../engine" }

kite-passenger = { path = "../../../passenger/rust" }

twilight-model = "0.11.0"
tokio = { version = "1.19.2", features = ["sync"] }
anyhow = "1.0.58"
dashmap = "5.3.4"
